### ISSUE TITLE
Query post that are 'not' featured

### ISSUE THREAD

**Issue by dmmarmol** [WPPress/featured-post#4]
Hi, sorry if this question is covered but i need to show all the post that are 'not' featured. Something like

'featured' => 'no',

is this actually possible?, because i can't manage to make it happen

Thanks!

**Comment by dmmarmol** [comment]
I've made an update to the code adding a new function called: 'set_not_featured()' that changes the attribute 'featured' to 'no' right after any post is created.

That way anyone can query all the post using 'WP_Query' or 'query_post' passing 'featured=no' as an argument. Because i saw that every new post created doesn't have the value 'no' in the 'featured' property unless you change the post to 'featured' and then to 'no' 'featured'.

(Sorry for my english). I hope this helps!
Bye

**Comment by IkeTen** [comment]
Brilliant and great update @dmmarmol and thanks for confirming it still works
